### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by topmask** [iamatulsingh/pinscrape#1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.local/lib/python3.9/site-packages/pinscrape/pinscrape.py", line 4, in <module>
    import cv2
  File "/.local/lib/python3.9/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by iamatulsingh** [comment]
Hi @topmask,
This error is not related to pinscrape package. It seems your system missing few library. You can take a look at the SO query for the same error or you can Google it.

https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo

**Comment by topmask** [comment]
Thank you

Made a python script p.py
why can't download


```
#!/usr/bin/python3

from pinscrape import pinscrape
is_downloaded = pinscrape.scraper.scrape("honey", "$HOME/Pinterest", 5)
if is_downloaded:
    print("\nDownloading completed !!")
else:
    print("\nNothing to download !!")
```

> ./p.py
Nothing to download !!

**Comment by iamatulsingh** [comment]
You have an error in your code. I'll update the code to throw error to let you understand but instead of 5 you have to provide proxy. definition is expecting things like in this `key=None, output_folder="", proxies={}, threads=10`. Instead of threads, you have given proxies as 5 which is causing the issue. Please use keywords to pass value like `pinscrape.scraper.scrape(key="honey", output_folder="$HOME/Pinterest", threads=5)`.
Also for different error you can open a new issue instead of using the previous error issue, that will help other person to search for it.

**Comment by topmask** [comment]
Thank you
